### ISSUE TITLE
Add General Census Info to the Home Page

### ISSUE THREAD

**Issue by anniejstein** [codeforsanjose/census2020#8] opened 2019-05-31 18:54 UTC
The website should a point of contact listed for people who have more questions.

We could provide more information about what is the Census.

We should also talk about all the benefits and research that based on Census data and the effects of miscalculation.

**Comment by aelar13** [comment] 2019-09-21 20:02
Here's some preliminary content for the Home Page. It is edited down from the info that Vilcia provided at the beginning of the project. Some of the other information could end up in Factoids. The focus was on keeping the content brief enough to avoid a long landing page.

Header: 
Be Counted San Jose!

Body: 
Every 10 years, the U.S. Census Bureau sets out to count every person living in the United States — regardless of age, citizenship status, and gender. Getting the 2020 Census right is important for all our communities — particularly those most likely to be undercounted. A 2020 Census undercount could put billions of federal dollars and congressional representation for California at risk!

This year, for the first time, residents can complete the census **online** via a computer or mobile device. The process is easy and quick! All you need is the ID code mailed to you by the Census Bureau, or your mailing address. Remember, to _include everyone living in your household_. That means children, teens, roommates, and so on. 

Click the "Take the Census Now" button to get started!

**Comment by turnerhayes** [comment] 2019-10-11 03:40
I think this is a duplicate of #55

**Closed as completed by turnerhayes** 2019-10-11 03:40 UTC
Labels: good first issue, HomePage
